sickgyun/sickgyun-client

apps/client/src/app/page.tsx
apps/client/src/components/common/Footer/index.tsx

feat(client): footer 개발

---

apps/client/package.json
apps/client/src/apis/core/index.ts
apps/client/src/constants/storage.ts
apps/client/src/exceptions/ApiException.ts
apps/client/src/exceptions/CustomException.ts
apps/client/src/exceptions/messages.ts
apps/client/src/exceptions/type.ts
apps/client/src/utils/common.ts
pnpm-lock.yaml

feat(client): instance 세팅

---

apps/client/src/app/mou-company/page.tsx
apps/client/src/app/page.tsx
apps/client/src/app/senior/[position]/page.tsx
apps/client/src/components/LoginBox/index.tsx
apps/client/src/components/MouCompanyCard/index.tsx
apps/client/src/components/SeniorCard/index.tsx
apps/client/src/components/common/Header/index.tsx
apps/client/src/store/UserInformation/index.ts

feat(client): 컴포넌트 모듈화

---

apps/client/src/app/page.tsx
apps/client/src/components/LoginBox/index.tsx
apps/client/src/hooks/api/user/useGetUserInformation.ts
apps/client/src/store/UserInformation/userInformationState.ts

로그인하였을 때 로그인 박스 퍼블리싱 로그인 박스 퍼블리싱하였습니다.

feat(client): 로그인하였을 때 로그인 박스 퍼블리싱 로그인 박스 퍼블리싱

---

apps/client/package.json
apps/client/src/app/mou-company/page.tsx
apps/client/src/app/page.tsx
apps/client/src/app/senior/[position]/page.tsx
apps/client/src/app/template.tsx
apps/client/src/components/LoginBox/index.tsx
apps/client/src/components/ProfileSettingModal/page.tsx
apps/client/src/constants/common.ts
apps/client/src/hooks/api/user/useGetUserInformation.ts
apps/client/src/store/UserInformation/userInformationState.ts
pnpm-lock.yaml

유저 정보를 입력 할 수 있는 프로필 설정 모달을 퍼블리싱 하였습니다.

feat(client): 프로필 설정 모달 퍼블리싱

---

apps/client/@types/global.d.ts
apps/client/src/app/mou-company/page.tsx
apps/client/src/app/senior/[position]/page.tsx
apps/client/src/components/SeniorRegisterButton/index.tsx
apps/client/src/components/SeniorRegisterModal/index.tsx
apps/client/src/components/UpdateProfileModal/index.tsx

선배 프로필 등록 버튼 & 선배 프로필 등록 모달 퍼블리싱을 하였습니다.

feat(client): 선배 프로필 등록 버튼 & 선배 프로필 등록 모달 퍼블리싱

---

apps/client/src/components/SeniorRegisterModal/index.tsx
apps/client/src/components/UpdateProfileModal/index.tsx
apps/client/src/hooks/api/senior/useRegisterSeniorMutation.ts
apps/client/src/hooks/api/user/useGetUserInformation.ts
apps/client/src/store/UserInformation/userInformationState.ts

feat(client): 선배 프로필 등록 api 연결

---

apps/client/src/app/page.tsx
apps/client/src/app/senior/page.tsx
apps/client/src/constants/common.ts
apps/client/src/hooks/api/senior/useGetSeniorList.ts

선배 프로필 조회 position 필터링 기능을 개발하였습니다.

feat(client): 선배 프로필 조회 position 필터링 기능 개발

---

apps/client/src/app/page.tsx

메인페이지 협약 회사 이동 유도 컴포넌트를 개발해야 합니다.

feat(client): 메인페이지 협약 회사 이동 유도 컴포넌트 개발

---

apps/client/src/app/senior/page.tsx
apps/client/src/components/SeniorCard/index.tsx
apps/client/src/components/SeniorDetailModal/index.tsx
apps/client/src/hooks/api/senior/useGetSeniorProfile.ts

feat(client): 선배 상세 조회 api 연결

---

apps/client/src/app/page.tsx
apps/client/src/app/student-profile/page.tsx
apps/client/src/components/JobPostingCard/index.tsx

채용 정보 리스트 & 채용 정보 박스 퍼블리싱을 하였습니다.

feat(client): 채용 정보 리스트 & 채용 정보 박스 퍼블리싱

---

apps/client/src/app/page.tsx
apps/client/src/components/JobPostingCard/index.tsx
apps/client/src/hooks/api/job-posting/useGetJobPostingList.ts

feat: 채용 공고 리스트 api 연결

---

apps/client/src/app/bsm-auth/page.tsx
apps/client/src/app/page.tsx
apps/client/src/app/student-profile/page.tsx
apps/client/src/components/JobPostingList/index.tsx
apps/client/src/components/StudentProfileDetailModal/StudentProfileDetailContents.tsx
apps/client/src/components/StudentProfileDetailModal/index.tsx
apps/client/src/components/StudentProfileList/index.tsx
apps/client/src/components/StudentProfileUpdateModal/index.tsx
apps/client/src/components/common/Header/index.tsx
apps/client/src/hooks/api/job-posting/useGetJobPostingList.ts
apps/client/src/hooks/api/student-profile/useGetStudentProfile.ts
apps/client/src/hooks/api/student-profile/useGetStudentProfileList.ts
apps/client/src/hooks/api/user/useGetUserInformation.ts
apps/client/src/libs/api/client.ts
apps/client/src/libs/storage/index.ts
apps/client/src/store/StudentProfile/useStudentProfile.ts
apps/client/src/store/UserInformation/useUserInformation.ts

suspense & useSusepnseQuery 사용하여 데이터 보장을 하였습니다.

feat(client): suspense & useSusepnseQuery 사용하여 데이터 보장

---

apps/client/__mocks__/fileMock.js
apps/client/__mocks__/styleMock.js
apps/client/jest.config.js
apps/client/package.json
apps/client/src/libs/api/client.ts
pnpm-lock.yaml

feat(client): jest 세팅

---

apps/client/next.config.js
apps/client/package.json
apps/client/src/app/layout.tsx
packages/design-token/.eslintrc.js
packages/design-token/package.json
packages/design-token/src/StyleProvider.tsx
packages/design-token/src/font.ts
packages/design-token/src/global.tsx
packages/design-token/src/index.ts
packages/design-token/src/reset.ts
packages/design-token/src/themes/colors.ts
packages/design-token/src/themes/fonts.ts
packages/design-token/src/themes/index.ts
packages/design-token/src/themes/theme.ts
packages/design-token/src/types/emotion.d.ts
packages/design-token/tsconfig.json
pnpm-lock.yaml

feat(design-token): design-token 세팅

---

apps/client/package.json
apps/client/src/app/template.tsx
apps/client/src/components/common/Header/index.tsx
apps/client/src/components/student-profile/StudentProfileUpdateModal/index.tsx
apps/client/src/store/StudentProfile/hasStudentProfileState.ts
apps/client/src/store/StudentProfile/studentProfileState.ts
apps/client/src/store/StudentProfile/useStudentProfile.ts
apps/client/src/store/UserInformation/isLoginState.ts
apps/client/src/store/UserInformation/useUserInformation.ts
apps/client/src/store/UserInformation/userInformationState.ts
pnpm-lock.yaml

feat(client): jotai로 마이그레이션

---

packages/ui/package.json
packages/ui/src/Portal/index.tsx
packages/ui/src/Portal/useDidMount.ts
pnpm-lock.yaml

feat(ui): portal 컴포넌트 개발

---

packages/ui/src/Flex/Flex.stories.tsx
packages/ui/src/Flex/index.tsx

- flex 컴포넌트 개발
- flex storybook 작성

feat(ui): flex 컴포넌트 개발

---

packages/ui/src/Stack/Stack.stories.tsx
packages/ui/src/Stack/index.tsx
packages/ui/src/index.ts

- stack 컴포넌트 개발
- stack storybook 작성

feat(ui): stack 컴포넌트 개발

---

packages/design-token/src/themes/colors.ts
packages/ui/src/Input/Input.stories.tsx
packages/ui/src/Input/index.tsx
packages/ui/src/Text/Text.stories.tsx
packages/ui/src/Text/index.tsx

- input 컴포넌트 개발
- input storybook 작성

feat(ui): input 컴포넌트 개발

---

packages/design-token/src/themes/fonts.ts
packages/ui/src/Button/GhostButton.tsx
packages/ui/src/Button/PrimaryButton.tsx
packages/ui/src/Confirm/Confirm.stories.tsx
packages/ui/src/Confirm/index.tsx
packages/ui/src/Input/index.tsx
packages/ui/src/Modal/index.tsx

- confirm 컴포넌트 개발
- confirm storybook 작성

feat(ui): confirm 컴포넌트 개발

---

packages/ui/src/Center/Center.stories.tsx
packages/ui/src/Center/index.tsx

- center 컴포넌트 개발
- center storybook 작성

feat(ui): center 컴포넌트 개발

---

apps/client/src/app/page.tsx
apps/client/src/app/student-profile/page.tsx
apps/client/src/components/common/Header/index.tsx
apps/client/src/components/main/LoginBox/index.tsx
apps/client/src/components/student-profile/StudentProfileUpdateModal/index.tsx
packages/ui/src/Button/PrimaryButton.tsx
packages/ui/src/Button/SecondaryButton.tsx
packages/ui/src/Button/index.tsx
packages/ui/src/Confirm/index.tsx

- secondary button 컴포넌트 개발
- 기존 ghost button과 secondary button 네이밍 변경: 기존 ghost -> secondary, secondary -> ghost

feat(client): secondary button 컴포넌트 개발

---

.vscode/settings.json
apps/client/src/app/page.tsx
apps/client/src/components/common/Footer/index.tsx
apps/client/src/components/common/Header/index.tsx
apps/client/src/components/job-posting/JobPostingCard/index.tsx
apps/client/src/components/main/LoginBox/index.tsx
apps/client/src/components/main/UserInformationUpdateModal/index.tsx
apps/client/src/components/student-profile/StudentProfileCard/index.tsx
apps/client/src/components/student-profile/StudentProfileCreateButton/index.tsx
apps/client/src/components/student-profile/StudentProfileCreateModal/index.tsx
apps/client/src/components/student-profile/StudentProfileDetailModal/StudentProfileDetailContents.tsx
apps/client/src/components/student-profile/StudentProfileDetailModal/index.tsx
apps/client/src/components/student-profile/StudentProfileList/index.tsx
apps/client/src/components/student-profile/StudentProfileUpdateButton/index.tsx
apps/client/src/components/student-profile/StudentProfileUpdateModal/index.tsx
packages/ui/.eslintrc.js
packages/ui/package.json
packages/ui/src/Confirm/index.tsx
packages/ui/src/Input/index.tsx
packages/ui/src/Link/index.tsx
packages/ui/src/Text/Text.stories.tsx
packages/ui/src/Text/index.tsx
packages/ui/src/index.ts
pnpm-lock.yaml

feat(ui): link 컴포넌트 개발

---

apps/client/@types/global.d.ts
apps/client/src/app/student-profile/page.tsx
apps/client/src/components/student-profile/StudentProfileUpdateModal/index.tsx
packages/ui/src/Button/GhostButton.tsx
packages/ui/src/Button/QuaternaryButton.tsx
packages/ui/src/Button/SecondaryButton.tsx
packages/ui/src/Button/index.tsx
packages/ui/src/Icons/ArrowLeft.tsx
packages/ui/src/Icons/ArrowRight.tsx
packages/ui/src/Icons/Heart.tsx
packages/ui/src/index.ts

- quaternary button 컴포넌트 개발
- Select, Button Todo 정리

feat(ui): quaternary button 컴포넌트 개발

---

.vscode/settings.json
apps/client/src/app/student-profile/page.tsx
apps/client/src/components/student-profile/StudentProfileDetailModal/StudentProfileDetailContents.tsx
apps/client/src/components/student-profile/StudentProfileDetailModal/index.tsx
apps/client/src/components/student-profile/StudentProfileList/index.tsx
apps/client/src/hocs/withSuspense.tsx

feat(client): 고차 컴포넌트를 통한 withSuspense 개발

---

apps/client/src/app/student-profile/create/page.tsx

feat(client): 프로필 생성 페이지 개발

---

apps/client/src/app/student-profile/create/page.tsx
apps/client/src/hocs/withAuth.tsx
apps/client/src/hocs/withLogin.tsx

feat(client): 고차 컴포넌트를 통한 withAuth 개발

---

.github/workflows/review.yml

ci(.github): review guide comment 자동화

---

packages/ui/src/Spacer/index.tsx
packages/ui/src/index.ts

- spacer 컴포넌트 개발
[chakra spacer](https://chakra-ui.com/docs/components/flex/usage#flex-and-spacer-vs-grid-vs-stack) 문서를 보시면 사용법을 이해하기 쉬울것같아용!

feat(ui): spacer 컴포넌트 개발

---

packages/ui/src/ErrorBoundary/index.tsx
packages/ui/src/Spacer/index.tsx

feat(ui): ErrorBoundary 컴포넌트 개발

---

packages/design-token/src/themes/index.ts
packages/design-token/src/themes/theme.ts
packages/design-token/src/themes/zIndex.ts
packages/design-token/src/types/emotion.d.ts
packages/ui/src/Modal/Modal.tsx

feat(common): zIndex design-token 추가

---

packages/ui/src/Spinner/Spinner.stories.tsx
packages/ui/src/Spinner/index.tsx

- spinner 컴포넌트 개발
- spinner storybook 작성

feat(ui): spinner 컴포넌트 개발

---

apps/client/src/components/student-profile/StudentProfileCard/index.tsx
apps/client/src/emotion/index.ts
apps/client/src/emotion/textEllipsis.ts
packages/ui/src/Text/index.tsx

-  textEllipsis 추가
- Text 컴포넌트 isEllipsis 추가

feat(client, ui): textEllipsis 추가

---

apps/client/src/hocs/withSuspense.tsx
packages/design-token/src/StyleProvider.tsx

feat(design-token): theme provider ssr 대응

---

apps/client/src/app/qna/page.tsx
apps/client/src/components/qna/QnaBox/index.tsx
apps/client/src/components/qna/QnaCategory/index.tsx
apps/client/src/components/qna/QnaListBox/index.tsx
apps/client/src/components/qna/QnaPostCard/index.tsx

fix(client): qna 페이지 전체적인 색감 수정

---

apps/client/package.json
apps/client/src/app/page.tsx
apps/client/src/components/main/LoginBox/index.tsx
apps/client/src/components/main/MainBanner/index.tsx
pnpm-lock.yaml

- 슬라이드 배너 개발
영상이 너무 커서 안들어가져요 슬라이드되는 배너와 컨트롤러를 개발하였습니다~

feat(client): 슬라이드 배너 개발

---

.vscode/settings.json
packages/ui/src/Link/index.tsx

feat(ui): link 컴포넌트에 ref prop 추가

---

.github/workflows/ci.yml
apps/client/src/app/providers.tsx

refactor(client): buildProvidersTree 세팅

---

apps/client/src/app/auth/page.tsx
apps/client/src/constants/storage.ts
apps/client/src/libs/api/client.ts
packages/libs/src/storage/index.ts

feat(client): accessToken refresh 기능 개발

---

apps/client/src/components/common/Header/index.tsx
apps/client/src/components/common/NotificationButton/index.tsx

- 알림 바로가기 버튼 안내 툴팁 추가
- 알림이 왔을때만 뜨도록 조건을 걸었어요.

feat(client): 알림 바로가기 버튼 안내 툴팁 추가

---

apps/client/src/components/coffeechat/CoffeechatAcceptConfirm/index.tsx
apps/client/src/components/coffeechat/CoffeechatMessageModal/index.tsx
apps/client/src/components/profile/ProfileDetailModal/index.tsx
apps/client/src/hooks/api/coffeechat/useAcceptCoffeechat.ts
packages/ui/src/Modal/ModalCloseButton.tsx

feat(client): 커피챗 수락시 메세지 보여주는 기능 개발

---

apps/client/src/hooks/api/auth/useLoginGoogle.ts
apps/client/src/hooks/api/coffeechat/useAcceptCoffeechat.ts
apps/client/src/hooks/api/coffeechat/useCancelCoffeechat.ts
apps/client/src/hooks/api/coffeechat/useCreateCoffeechat.ts
apps/client/src/hooks/api/coffeechat/useGetReceiveCoffeechatList.ts
apps/client/src/hooks/api/coffeechat/useGetSendCoffeechatList.ts
apps/client/src/hooks/api/coffeechat/useRejectCoffeechat.ts
apps/client/src/hooks/api/profile/useCreateProfile.ts
apps/client/src/hooks/api/profile/useDeleteProfileMine.ts
apps/client/src/hooks/api/profile/useGetProfile.ts
apps/client/src/hooks/api/profile/useGetProfileList.ts
apps/client/src/hooks/api/profile/useGetProfileMine.ts
apps/client/src/hooks/api/profile/useUpdateProfile.ts
apps/client/src/hooks/api/qna/useCreateQna.ts
apps/client/src/hooks/api/recruit/useGetRecuritList.ts
apps/client/src/hooks/api/user/useGetUser.ts

refactor(client): react-query 타입 정리

---

apps/client/src/components/coffeechat/CoffeechatMessageModal/index.tsx
apps/client/src/components/coffeechat/CoffeechatSendConfirm/index.tsx
apps/client/src/components/profile/ProfileDetailModal/index.tsx

- 커피챗 메세지 보내기 부분에 안내 문구 추가
- Modal, Confirm 네이밍 명시적으로 변경

feat(client): 커피챗 메세지 보내기 부분에 안내 문구 추가

---

apps/client/src/components/coffeechat/CoffeechatReceiveCard/index.tsx
apps/client/src/components/coffeechat/CoffeechatReceiveList/index.tsx
apps/client/src/hooks/api/user/useGetUser.ts
apps/client/src/types/coffeechat.ts

- 커피챗 승인 완료된 카드에 메세지 보여주는 기능 추가

feat(client): 커피챗 승인 완료된 카드에 메세지 보여주는 기능 추가

---

apps/admin/src/app/layout.tsx
apps/admin/src/providers/QueryClientProvider.tsx
apps/client/src/app/auth/page.tsx
apps/client/src/app/layout.tsx
apps/client/src/app/profile/create/page.tsx
apps/client/src/app/profile/page.tsx
apps/client/src/app/profile/update/page.tsx
apps/client/src/app/providers.tsx
apps/client/src/components/common/Header/index.tsx
apps/client/src/components/main/LoginBox/index.tsx
apps/client/src/components/profile/ProfileDetailContent/index.tsx
apps/client/src/components/profile/ProfileDetailModal/index.tsx
apps/client/src/components/recurit/RecuritCard/index.tsx
apps/client/src/components/recurit/RecuritList/index.tsx
apps/client/src/hocs/withAuth.tsx
apps/client/src/hooks/api/user/useGetUser.ts
apps/client/src/hooks/common/useUser.ts
apps/client/src/providers/QueryClientProvider.tsx
apps/client/src/store/user/index.ts
apps/client/src/store/user/isLoginAtom.ts
apps/client/src/store/user/userAtom.ts
apps/client/src/utils/getGoogleAccessToken.ts
packages/ui/src/Portal/index.tsx
packages/ui/src/Spinner/index.tsx
packages/ui/src/Tooltip/index.tsx

- 메인 페이지 로딩 처리
- useUser 리팩토링
network에서 3g slow를 통해 테스트를 진행했어요.
https://github.com/sickgyun/sickgyun-client/assets/102217654/be169e43-fea2-4ef7-b844-657cf0c0f11a
https://github.com/sickgyun/sickgyun-client/assets/102217654/47f33f55-34e6-4159-8ed4-e007cda4a9e3

fix(client): 메인 페이지 로딩 처리

---

apps/client/src/components/common/Banners/ErrorReportBanner/index.tsx
apps/client/src/components/common/Banners/UserInterviewBanner/index.tsx
apps/client/src/hooks/api/auth/useLoginGoogle.ts
apps/client/src/hooks/api/coffeechat/useGetReceiveCoffeechatList.ts
apps/client/src/hooks/api/coffeechat/useGetSendCoffeechatList.ts
apps/client/src/hooks/api/profile/useCreateProfile.ts
apps/client/src/hooks/api/profile/useDeleteProfileMine.ts
apps/client/src/hooks/api/profile/useGetProfileList.ts
apps/client/src/hooks/api/profile/useGetProfileMine.ts
apps/client/src/hooks/api/profile/useUpdateProfile.ts
apps/client/src/hooks/api/qna/useCreateQna.ts
apps/client/src/hooks/api/recruit/useGetRecuritList.ts
apps/client/src/hooks/api/user/useGetUser.ts
apps/client/src/libs/api/client.ts

- api 엔드포인트 형식 변경
- banner padding 스타일 수정

fix(client): api 엔드포인트 형식 변경

---

apps/client/src/components/coffeechat/CoffeechatReceiveList/index.tsx
apps/client/src/components/common/Header/index.tsx

- 프로필 생성시 알림 아이콘을 보여주는 조건 수정
- 프로필 등록하지 않은 상태에서 커피챗 요청 알림으로 가면 프로필 등록 유도 버튼이 보이도록 추가

fix(client): 프로필 생성시 알림 아이콘을 보여주는 조건 수정

---

apps/client/src/components/profile/ProfileDetailContent/index.tsx

fix(client): 프로필 삭제 버튼 아이콘 수정

---

apps/client/src/app/layout.tsx
apps/client/src/components/common/ScrollToTop/index.tsx

- 페이지 이동 감지 시 스크롤 최상위로 올라가는 컴포넌트 개발
- ScrollToTop 컴포넌트 개발

feat(client): 페이지 이동 감지 시 스크롤 최상위로 올라가는 컴포넌트 개발

---

apps/client/src/components/profile/ProfileDetailContent/index.tsx

- 프로필 수정 후 프로필 상세 모달에 들어갔을때 생기는 레이아웃 쉬프트 수정

fix(client): 프로필 수정 후 프로필 상세 모달에 들어갔을때 생기는 레이아웃 쉬프트 수정

---

apps/client/src/app/profile/create/page.tsx
apps/client/src/app/profile/update/page.tsx
apps/client/src/app/qna/[id]/page.tsx
apps/client/src/components/profile/ProfileForm/index.tsx
apps/client/src/components/profile/ProfileImageUploader/index.tsx
apps/client/src/components/qna/QnaListBox/index.tsx
apps/client/src/components/qna/QnaPostCard/index.tsx
apps/client/src/hooks/api/image/useUploadImage.ts
apps/client/src/hooks/api/profile/useCreateProfile.ts
apps/client/src/hooks/api/profile/useUpdateProfile.ts
apps/client/src/types/profile.ts
packages/design-token/src/global.tsx
packages/ui/src/Button/GhostButton.tsx
packages/ui/src/Button/SecondaryButton.tsx
packages/ui/src/Button/index.tsx
packages/ui/src/Input/index.tsx
packages/ui/src/Modal/ModalCloseButton.tsx
packages/ui/src/Select/index.tsx
packages/ui/src/Textarea/index.tsx
packages/ui/src/Tooltip/index.tsx

- 프로필 이미지 업로더 개발
- 폼 필드 디자인 시스템 스타일 수정

feat(client): 프로필 이미지 업로더 개발

---

apps/client/src/app/page.tsx
apps/client/src/components/common/FullHeightSpinner/index.tsx
apps/client/src/components/profile/ProfileDetailContent/index.tsx

- full height spinner 컴포넌트 개발
- 채용 공고 레이아웃 쉬프트 수정

feat(client): full height spinner 컴포넌트 개발

---

apps/client/src/components/common/Banners/QnaBanner/index.tsx
apps/client/src/hooks/common/useLogAnalyticsEvent.ts
apps/client/src/libs/api/client.ts
apps/client/src/libs/logging/logAnalyticsEvent.ts
apps/client/src/libs/logging/type.ts
apps/client/src/libs/logging/useLogAnalyticsEvent.ts
apps/client/src/utils/isDev.ts
apps/client/src/utils/isProd.ts
pnpm-lock.yaml

- 로깅 모듈 개발
```tsx
const { logShowEvent, logClickEvent } = useLogAnalyticsEvent();
useEffect(() => {
logShowEvent({ name: "hi", params: { hi: "hi" } });
}, [])
const handleClick = () => {
logClickEvent({ name: "hi", params: { hi: "hi" } });
}
```

feat(client): 로깅 모듈 개발

---

apps/client/src/app/notification/page.tsx
apps/client/src/components/coffeechat/CoffeechatReceiveCard/index.tsx
apps/client/src/components/coffeechat/CoffeechatSendCard/index.tsx
apps/client/src/components/coffeechat/CoffeechatSendList/index.tsx

feat(client):  커피챗 신청 카드 컴포넌트 수락, 거절 상태 추가

---

apps/client/src/hooks/api/auth/useLoginGoogle.ts
apps/client/src/hooks/api/coffeechat/useAcceptCoffeechat.ts
apps/client/src/hooks/api/coffeechat/useCancelCoffeechat.ts
apps/client/src/hooks/api/coffeechat/useCreateCoffeechat.ts
apps/client/src/hooks/api/coffeechat/useGetReceiveCoffeechatList.ts
apps/client/src/hooks/api/coffeechat/useGetSendCoffeechatList.ts
apps/client/src/hooks/api/coffeechat/useRejectCoffeechat.ts
apps/client/src/hooks/api/image/useUploadImage.ts
apps/client/src/hooks/api/profile/useCreateProfile.ts
apps/client/src/hooks/api/profile/useDeleteProfileMine.ts
apps/client/src/hooks/api/profile/useGetProfile.ts
apps/client/src/hooks/api/profile/useGetProfileList.ts
apps/client/src/hooks/api/profile/useGetProfileMine.ts
apps/client/src/hooks/api/profile/useUpdateProfile.ts
apps/client/src/hooks/api/qna/useCreateQna.ts
apps/client/src/hooks/api/recruit/useGetRecuritList.ts
apps/client/src/hooks/api/user/useGetUser.ts
apps/client/src/hooks/api/user/useUpdateUserContact.ts
apps/client/src/libs/api/client.ts
apps/client/src/libs/exceptions/ApiException.ts
apps/client/src/libs/exceptions/index.ts
apps/client/src/libs/exceptions/type.ts

- 리프래쉬 토큰 재발급 로직 리팩토링
- ApiErrorScheme 적용되지 않은 곳들에 적용

refactor(client): 리프래쉬 토큰 재발급 로직 리팩토링

---

apps/client/src/components/common/LogClickEvent/index.tsx

- log click event 컴포넌트 개발
- 로깅을 리액트 컴포넌트로 선언적으로 할 수 있도록 도와주는 컴포넌트에요.
```tsx
<LogClickEvent name="click_event" params={{ userId: 1 }}>
클릭
</LogClickEvent>
```

feat(client): log click event 컴포넌트 개발

---

apps/client/src/libs/logging/useLogAnalyticsEvent.ts

- 로깅 default params에 date, time 추가

feat(client): 로깅 default params에 date, time 추가

---

apps/client/src/components/profile/ProfileCard/index.tsx
apps/client/src/components/profile/ProfileList/index.tsx

feat(client): 프로필 카드 클릭 로깅 추가

---

apps/client/src/app/error.tsx
apps/client/src/app/mobile/page.tsx
apps/client/src/app/not-found.tsx
apps/client/src/components/profile/ProfileDetailContent/index.tsx
apps/client/src/libs/api/client.ts
apps/client/src/utils/convertNewlineToJsx.tsx

- convertNewlineToJsx 개발
https://www.slash.page/ko/libraries/react/react/src/utils/convertnewlinetojsx.i18n

feat(client): convertNewlineToJsx 개발

---

package.json
pnpm-lock.yaml

Reverts sickgyun/sickgyun-client#328

Revert "chore(deps): update dependency ts-jest to v29.1.2"

---

apps/client/src/app/mobile/page.tsx
apps/client/src/components/coffeechat/CoffeechatCancelConfirm/index.tsx
apps/client/src/components/coffeechat/CoffeechatContactFormModal/index.tsx
apps/client/src/components/coffeechat/CoffeechatRejectConfirm/index.tsx
apps/client/src/components/coffeechat/CoffeechatSendConfirm/index.tsx
apps/client/src/components/common/Banners/QnaBanner/index.tsx
apps/client/src/components/common/Banners/UserInterviewBanner/index.tsx

- 연락처 입력 form 필수 값 입력하지 않았을 시 토스트 에러 처리
https://github.com/sickgyun/sickgyun-client/assets/102217654/06680cd8-3ddf-419e-a414-7076592df772

feat(client): 연락처 입력 form 필수 값 입력하지 않았을 시 토스트 에러 처리

---

apps/client/src/app/error.tsx
apps/client/src/app/mobile/page.tsx
apps/client/src/app/not-found.tsx
apps/client/src/app/notification/page.tsx
apps/client/src/app/profile/create/page.tsx
apps/client/src/app/profile/update/page.tsx
apps/client/src/components/coffeechat/CoffeechatReceiveList/index.tsx
apps/client/src/components/common/Banners/QnaBanner/index.tsx
apps/client/src/components/main/LoginBox/index.tsx
packages/ui/src/Text/index.tsx

- 로그인 박스 프로필, 연락처 추가, 수정 유도 버튼으로 수정

fix(client): 로그인 박스 프로필, 연락처 추가, 수정 유도 버튼으로 수정

---

packages/design-token/src/font.ts
packages/design-token/src/global.tsx

fix(design-token): 폼 필드에 폰트 적용되지 않는 문제 수정

---

packages/ui/src/Modal/Modal.tsx

feat(client): 모달창이 열려있을 때 body 스크롤 방지

---

apps/client/src/app/email/page.tsx

feat(client): 이메일에서 사이트로 들어오는 유입률 로깅

---

docs/storybook/stories/Alert.stories.tsx
docs/storybook/stories/Button.stories.tsx
docs/storybook/stories/Confirm.stories.tsx
docs/storybook/stories/InfoBox.stories.tsx
docs/storybook/stories/Input.stories.tsx
docs/storybook/stories/Modal.stories.tsx
docs/storybook/stories/Select.stories.tsx
docs/storybook/stories/Textarea.stories.tsx

fix(storybook): 스토리북 ui 깨짐 수정

---

apps/client/src/app/profile/create/page.tsx
apps/client/src/app/profile/update/page.tsx
apps/client/src/components/qna/QnaPostCategory/index.tsx
packages/ui/src/Tooltip/index.tsx

feat(client): 프로필 수정, 등록 페이지에 뒤로가기 버튼 추가

---

apps/client/src/app/profile/create/page.tsx
apps/client/src/components/notification/NotificationCoffeechatPendingPreview/index.tsx

feat(client): 프로필 등록 플로우에 연락처 입력 스텝 추가

---

apps/client/src/app/mobile/page.tsx
apps/client/src/components/coffeechat/CoffeechatContactFormModal/index.tsx
apps/client/src/components/common/Banners/ErrorReportBanner/index.tsx
apps/client/src/components/common/Banners/UserInterviewBanner/index.tsx
apps/client/src/components/main/LoginBox/index.tsx
apps/client/src/components/notification/NotificationCoffeechatAcceptPreview/index.tsx
apps/client/src/components/notification/NotificationCoffeechatPendingPreview/index.tsx
apps/client/src/components/notification/NotificationCoffeechatRejectPreview/index.tsx
apps/client/src/components/profile/ProfileDetailModal/index.tsx
apps/client/src/components/profile/ProfileNavigationBar/index.tsx
apps/client/src/components/recurit/RecuritCard/index.tsx
packages/design-token/src/themes/fonts.ts
packages/ui/src/Alert/index.tsx
packages/ui/src/Confirm/index.tsx

feat(design-token, client): 폰트 토큰 업데이트

---

docs/storybook/stories/Chip.stories.tsx
docs/storybook/stories/Switch.stories.tsx
packages/ui/src/Chip/index.tsx
packages/ui/src/index.ts

- 칩 디자인 시스템 컴포넌트 개발
- 칩 디자인 시스템 컴포넌트 스토리북 작성

feat(ui, storybook): 칩 디자인 시스템 컴포넌트 개발

---

apps/client/src/app/notification/page.tsx
apps/client/src/app/profile/page.tsx
apps/client/src/components/profile/ProfileDetailContent/index.tsx
apps/client/src/components/profile/ProfileList/index.tsx
apps/client/src/components/profile/ProfileNavigationBar/index.tsx
apps/client/src/constants/profile.ts
apps/client/src/types/profile.ts

- 프로필 페이지 부마위키, 식견 프로모션 개발
https://github.com/sickgyun/sickgyun-client/assets/102217654/45048e1f-3157-4d8f-84a0-bade1d62efc1

feat(client): 프로필 페이지 부마위키, 식견 프로모션 개발

---

apps/client/src/components/notification/NotificationCoffeechatAcceptPreview/index.tsx
apps/client/src/components/notification/NotificationCoffeechatRejectPreview/index.tsx
docs/storybook/stories/InlineBanner.stories.tsx
packages/design-token/src/themes/colors.ts
packages/ui/src/Chip/index.tsx
packages/ui/src/InlineBanner/index.tsx
packages/ui/src/index.ts

- inline banner 디자인 시스템 컴포넌트 개발
- inline banner 스토리북 작성
- 컬러 토큰 yellowBackground, primaryBackground, redBackground 추가

feat(client, ui, storybook, design-token): inline banner 디자인 시스템 컴포넌트 개발

---

apps/client/src/app/page.tsx

feat(client): 메인 페이지에 로그인 안내 인라인 배너 추가

---

apps/client/package.json
apps/client/src/components/coffeechat/CoffeechatAcceptConfirm/index.tsx
apps/client/src/components/coffeechat/CoffeechatSendConfirm/index.tsx
apps/client/src/hooks/common/useShowConfettiEffect.ts
pnpm-lock.yaml

feat(client): 커피챗 요청, 수락시 폭죽 이펙트 추가
